print("hello world")
print("hello world")
print("hello")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")

print('hi')
print('hi')
print('hi')
print('hi')
